//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Socioboard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/CompanyDashboard.asmx")]
        public string Socioboard_Api_CompanyDashboard_CompanyDashboard {
            get {
                return ((string)(this["Socioboard_Api_CompanyDashboard_CompanyDashboard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/Companypage.asmx")]
        public string Socioboard_Api_Companypage_Companypage {
            get {
                return ((string)(this["Socioboard_Api_Companypage_Companypage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/DropboxAccount.asmx")]
        public string Socioboard_Api_DropboxAccount_DropboxAccount {
            get {
                return ((string)(this["Socioboard_Api_DropboxAccount_DropboxAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/Tumblr.asmx")]
        public string Socioboard_Api_Tumblr_Tumblr {
            get {
                return ((string)(this["Socioboard_Api_Tumblr_Tumblr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/Dropbox.asmx")]
        public string Socioboard_Api_Dropbox_Dropbox {
            get {
                return ((string)(this["Socioboard_Api_Dropbox_Dropbox"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.socioboard.com/Services/Facebook.asmx")]
        public string Socioboard_Api_Facebook_Facebook {
            get {
                return ((string)(this["Socioboard_Api_Facebook_Facebook"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/Linkedin.asmx")]
        public string Socioboard_Api_Linkedin_Linkedin {
            get {
                return ((string)(this["Socioboard_Api_Linkedin_Linkedin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/TumblrAccount.asmx")]
        public string Socioboard_Api_TumblrAccount_TumblrAccount {
            get {
                return ((string)(this["Socioboard_Api_TumblrAccount_TumblrAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/YoutubeAccount.asmx")]
        public string Socioboard_Api_YoutubeAccount_YoutubeAccount {
            get {
                return ((string)(this["Socioboard_Api_YoutubeAccount_YoutubeAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/YoutubeChannel.asmx")]
        public string Socioboard_Api_YoutubeChannel_YoutubeChannel {
            get {
                return ((string)(this["Socioboard_Api_YoutubeChannel_YoutubeChannel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/TumblrFeed.asmx")]
        public string Socioboard_Api_TumblrFeed_TumblrFeed {
            get {
                return ((string)(this["Socioboard_Api_TumblrFeed_TumblrFeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/TwitterDirectMessages.asmx")]
        public string Socioboard_Api_TwitterDirectMessages_TwitterDirectMessages {
            get {
                return ((string)(this["Socioboard_Api_TwitterDirectMessages_TwitterDirectMessages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/LinkedinAccount.asmx")]
        public string Socioboard_Api_LinkedinAccount_LinkedinAccount {
            get {
                return ((string)(this["Socioboard_Api_LinkedinAccount_LinkedinAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/LinkedInFeed.asmx")]
        public string Socioboard_Api_LinkedInFeed_LinkedInFeed {
            get {
                return ((string)(this["Socioboard_Api_LinkedInFeed_LinkedInFeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/InstagramAccount.asmx")]
        public string Socioboard_Api_InstagramAccount_InstagramAccount {
            get {
                return ((string)(this["Socioboard_Api_InstagramAccount_InstagramAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.socioboard.com/Services/InstagramFeed.asmx")]
        public string Socioboard_Api_InstagramFeed_InstagramFeed {
            get {
                return ((string)(this["Socioboard_Api_InstagramFeed_InstagramFeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/BusinessSetting.asmx")]
        public string Socioboard_Api_BusinessSetting_BusinessSetting {
            get {
                return ((string)(this["Socioboard_Api_BusinessSetting_BusinessSetting"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/Drafts.asmx")]
        public string Socioboard_Api_Drafts_Drafts {
            get {
                return ((string)(this["Socioboard_Api_Drafts_Drafts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.socioboard.com/Services/Youtube.asmx")]
        public string Socioboard_Api_Youtube_Youtube {
            get {
                return ((string)(this["Socioboard_Api_Youtube_Youtube"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/TwitterStats.asmx")]
        public string Socioboard_Api_TwitterStats_TwitterStats {
            get {
                return ((string)(this["Socioboard_Api_TwitterStats_TwitterStats"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/TeamMemberProfile.asmx")]
        public string Socioboard_Api_TeamMemberProfile_TeamMemberProfile {
            get {
                return ((string)(this["Socioboard_Api_TeamMemberProfile_TeamMemberProfile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/TwitterAccount.asmx")]
        public string Socioboard_Api_TwitterAccount_TwitterAccount {
            get {
                return ((string)(this["Socioboard_Api_TwitterAccount_TwitterAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/InstagramComment.asmx")]
        public string Socioboard_Api_InstagramComment_InstagramComment {
            get {
                return ((string)(this["Socioboard_Api_InstagramComment_InstagramComment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/LinkedinCompanyPage.asmx")]
        public string Socioboard_Api_LinkedinCompanyPage_LinkedinCompanyPage {
            get {
                return ((string)(this["Socioboard_Api_LinkedinCompanyPage_LinkedinCompanyPage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/TwitterMessage.asmx")]
        public string Socioboard_Api_TwitterMessage_TwitterMessage {
            get {
                return ((string)(this["Socioboard_Api_TwitterMessage_TwitterMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/PaymentTransaction.asmx")]
        public string Socioboard_Api_PaymentTransaction_PaymentTransaction {
            get {
                return ((string)(this["Socioboard_Api_PaymentTransaction_PaymentTransaction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/ArchiveMessage.asmx")]
        public string Socioboard_Api_ArchiveMessage_ArchiveMessage {
            get {
                return ((string)(this["Socioboard_Api_ArchiveMessage_ArchiveMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.socioboard.com/Services/User.asmx")]
        public string Socioboard_Api_User_User {
            get {
                return ((string)(this["Socioboard_Api_User_User"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/TicketAssigneeStatus.asmx")]
        public string Socioboard_Api_TicketAssigneeStatus_TicketAssigneeStatus {
            get {
                return ((string)(this["Socioboard_Api_TicketAssigneeStatus_TicketAssigneeStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/TwitterFeed.asmx")]
        public string Socioboard_Api_TwitterFeed_TwitterFeed {
            get {
                return ((string)(this["Socioboard_Api_TwitterFeed_TwitterFeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/Invitation.asmx")]
        public string Socioboard_Api_Invitation_Invitation {
            get {
                return ((string)(this["Socioboard_Api_Invitation_Invitation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/AdminNews.asmx")]
        public string Socioboard_Api_AdminNews_AdminNews {
            get {
                return ((string)(this["Socioboard_Api_AdminNews_AdminNews"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/AdminPackageDetails.asmx")]
        public string Socioboard_Api_AdminPackageDetails_AdminPackageDetails {
            get {
                return ((string)(this["Socioboard_Api_AdminPackageDetails_AdminPackageDetails"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/AdminUserDetails.asmx")]
        public string Socioboard_Api_AdminUserDetails_AdminUserDetails {
            get {
                return ((string)(this["Socioboard_Api_AdminUserDetails_AdminUserDetails"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/Ads.asmx")]
        public string Socioboard_Api_Ads_Ads {
            get {
                return ((string)(this["Socioboard_Api_Ads_Ads"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/Coupon.asmx")]
        public string Socioboard_Api_Coupon_Coupon {
            get {
                return ((string)(this["Socioboard_Api_Coupon_Coupon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/NewsLetter.asmx")]
        public string Socioboard_Api_NewsLetter_NewsLetter {
            get {
                return ((string)(this["Socioboard_Api_NewsLetter_NewsLetter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/GroupProfile.asmx")]
        public string Socioboard_Api_GroupProfile_GroupProfile {
            get {
                return ((string)(this["Socioboard_Api_GroupProfile_GroupProfile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/FbPageLiker.asmx")]
        public string Socioboard_Api_FbPageLiker_FbPageLiker {
            get {
                return ((string)(this["Socioboard_Api_FbPageLiker_FbPageLiker"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/FbPageComment.asmx")]
        public string Socioboard_Api_FbPageComment_FbPageComment {
            get {
                return ((string)(this["Socioboard_Api_FbPageComment_FbPageComment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/FacebookAccount.asmx")]
        public string Socioboard_Api_FacebookAccount_FacebookAccount {
            get {
                return ((string)(this["Socioboard_Api_FacebookAccount_FacebookAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/FbPagePost.asmx")]
        public string Socioboard_Api_FbPagePost_FbPagePost {
            get {
                return ((string)(this["Socioboard_Api_FbPagePost_FbPagePost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.socioboard.com/Services/Groups.asmx")]
        public string Socioboard_Api_Groups_Groups {
            get {
                return ((string)(this["Socioboard_Api_Groups_Groups"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/FacebookFeed.asmx")]
        public string Socioboard_Api_FacebookFeed_FacebookFeed {
            get {
                return ((string)(this["Socioboard_Api_FacebookFeed_FacebookFeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/GroupScheduleMessage.asmx")]
        public string Socioboard_Api_GroupScheduleMessage_GroupScheduleMessage {
            get {
                return ((string)(this["Socioboard_Api_GroupScheduleMessage_GroupScheduleMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/FacebookMessage.asmx")]
        public string Socioboard_Api_FacebookMessage_FacebookMessage {
            get {
                return ((string)(this["Socioboard_Api_FacebookMessage_FacebookMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/GooglePlusAccount.asmx")]
        public string Socioboard_Api_GooglePlusAccount_GooglePlusAccount {
            get {
                return ((string)(this["Socioboard_Api_GooglePlusAccount_GooglePlusAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/SocialProfile.asmx")]
        public string Socioboard_Api_SocialProfile_SocialProfile {
            get {
                return ((string)(this["Socioboard_Api_SocialProfile_SocialProfile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/SentimentalAnalysis.asmx")]
        public string Socioboard_Api_SentimentalAnalysis_SentimentalAnalysis {
            get {
                return ((string)(this["Socioboard_Api_SentimentalAnalysis_SentimentalAnalysis"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/Tasks.asmx")]
        public string Socioboard_Api_Tasks_Tasks {
            get {
                return ((string)(this["Socioboard_Api_Tasks_Tasks"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/TaskComment.asmx")]
        public string Socioboard_Api_TaskComment_TaskComment {
            get {
                return ((string)(this["Socioboard_Api_TaskComment_TaskComment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/ScheduledMessage.asmx")]
        public string Socioboard_Api_ScheduledMessage_ScheduledMessage {
            get {
                return ((string)(this["Socioboard_Api_ScheduledMessage_ScheduledMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.socioboard.com/Services/Instagram.asmx")]
        public string Socioboard_Api_Instagram_Instagram {
            get {
                return ((string)(this["Socioboard_Api_Instagram_Instagram"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/Affiliates.asmx")]
        public string Socioboard_Api_Affiliates_Affiliates {
            get {
                return ((string)(this["Socioboard_Api_Affiliates_Affiliates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/Team.asmx")]
        public string Socioboard_Api_Team_Team {
            get {
                return ((string)(this["Socioboard_Api_Team_Team"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/MailSender.asmx")]
        public string Socioboard_Api_MailSender_MailSender {
            get {
                return ((string)(this["Socioboard_Api_MailSender_MailSender"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/Twitter.asmx")]
        public string Socioboard_Api_Twitter_Twitter {
            get {
                return ((string)(this["Socioboard_Api_Twitter_Twitter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/Admin.asmx")]
        public string Socioboard_Api_Admin_Admin {
            get {
                return ((string)(this["Socioboard_Api_Admin_Admin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.socioboard.com/services/EwalletWithdrawRequest.asmx")]
        public string Socioboard_Api_EwalletWithdrawRequest_EwalletWithdrawRequest {
            get {
                return ((string)(this["Socioboard_Api_EwalletWithdrawRequest_EwalletWithdrawRequest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.socioboard.com/services/GooglePlusActivities.asmx")]
        public string Socioboard_Api_GooglePlusActivities_GooglePlusActivities {
            get {
                return ((string)(this["Socioboard_Api_GooglePlusActivities_GooglePlusActivities"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.socioboard.com/services/GooglePlus.asmx")]
        public string Socioboard_Api_GooglePlus_GooglePlus {
            get {
                return ((string)(this["Socioboard_Api_GooglePlus_GooglePlus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.socioboard.com/services/InboxMessages.asmx")]
        public string Socioboard_Api_InboxMessages_InboxMessages {
            get {
                return ((string)(this["Socioboard_Api_InboxMessages_InboxMessages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.socioboard.com/services/LinkedinMessage.asmx")]
        public string Socioboard_Api_LinkedinMessage_LinkedinMessage {
            get {
                return ((string)(this["Socioboard_Api_LinkedinMessage_LinkedinMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.socioboard.com/services/discoverysearch.asmx")]
        public string Socioboard_Api_DiscoverySearch_DiscoverySearch {
            get {
                return ((string)(this["Socioboard_Api_DiscoverySearch_DiscoverySearch"]));
            }
        }
    }
}
