//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace Socioboard.Api.Twitter {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TwitterSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OAuthBase))]
    public partial class Twitter : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTwitterRedirectUrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddTwitterAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback TwitterLogInOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTwitterFeedsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserRetweetsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTwitterMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTwitterDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SheduleTwitterMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserProileOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserTweetsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserFeedOperationCompleted;
        
        private System.Threading.SendOrPostCallback TwitterComposeMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback TwitterComposeMessageRssOperationCompleted;
        
        private System.Threading.SendOrPostCallback TwitterRecentFollowerOperationCompleted;
        
        private System.Threading.SendOrPostCallback TwitterReplyUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback TwitterReteet_postOperationCompleted;
        
        private System.Threading.SendOrPostCallback TwitterFavorite_postOperationCompleted;
        
        private System.Threading.SendOrPostCallback SpamUser_postOperationCompleted;
        
        private System.Threading.SendOrPostCallback TwitterProfileDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTwitterAccountByAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback TicketTwitterReplyOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserMentionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserFollowersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserRetweetOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserFollowersDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTwitterDirectMessageSentOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTwittwrDirectMessageRecievedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Twitter() {
            this.Url = global::Socioboard.Properties.Settings.Default.Socioboard_Api_Twitter_Twitter;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTwitterRedirectUrlCompletedEventHandler GetTwitterRedirectUrlCompleted;
        
        /// <remarks/>
        public event AddTwitterAccountCompletedEventHandler AddTwitterAccountCompleted;
        
        /// <remarks/>
        public event TwitterLogInCompletedEventHandler TwitterLogInCompleted;
        
        /// <remarks/>
        public event getTwitterFeedsCompletedEventHandler getTwitterFeedsCompleted;
        
        /// <remarks/>
        public event getUserRetweetsCompletedEventHandler getUserRetweetsCompleted;
        
        /// <remarks/>
        public event getTwitterMessagesCompletedEventHandler getTwitterMessagesCompleted;
        
        /// <remarks/>
        public event getTwitterDataCompletedEventHandler getTwitterDataCompleted;
        
        /// <remarks/>
        public event SheduleTwitterMessageCompletedEventHandler SheduleTwitterMessageCompleted;
        
        /// <remarks/>
        public event getUserProileCompletedEventHandler getUserProileCompleted;
        
        /// <remarks/>
        public event getUserTweetsCompletedEventHandler getUserTweetsCompleted;
        
        /// <remarks/>
        public event getUserFeedCompletedEventHandler getUserFeedCompleted;
        
        /// <remarks/>
        public event TwitterComposeMessageCompletedEventHandler TwitterComposeMessageCompleted;
        
        /// <remarks/>
        public event TwitterComposeMessageRssCompletedEventHandler TwitterComposeMessageRssCompleted;
        
        /// <remarks/>
        public event TwitterRecentFollowerCompletedEventHandler TwitterRecentFollowerCompleted;
        
        /// <remarks/>
        public event TwitterReplyUpdateCompletedEventHandler TwitterReplyUpdateCompleted;
        
        /// <remarks/>
        public event TwitterReteet_postCompletedEventHandler TwitterReteet_postCompleted;
        
        /// <remarks/>
        public event TwitterFavorite_postCompletedEventHandler TwitterFavorite_postCompleted;
        
        /// <remarks/>
        public event SpamUser_postCompletedEventHandler SpamUser_postCompleted;
        
        /// <remarks/>
        public event TwitterProfileDetailsCompletedEventHandler TwitterProfileDetailsCompleted;
        
        /// <remarks/>
        public event UpdateTwitterAccountByAdminCompletedEventHandler UpdateTwitterAccountByAdminCompleted;
        
        /// <remarks/>
        public event TicketTwitterReplyCompletedEventHandler TicketTwitterReplyCompleted;
        
        /// <remarks/>
        public event getUserMentionsCompletedEventHandler getUserMentionsCompleted;
        
        /// <remarks/>
        public event getUserFollowersCompletedEventHandler getUserFollowersCompleted;
        
        /// <remarks/>
        public event getUserRetweetCompletedEventHandler getUserRetweetCompleted;
        
        /// <remarks/>
        public event getUserFollowersDataCompletedEventHandler getUserFollowersDataCompleted;
        
        /// <remarks/>
        public event getTwitterDirectMessageSentCompletedEventHandler getTwitterDirectMessageSentCompleted;
        
        /// <remarks/>
        public event getTwittwrDirectMessageRecievedCompletedEventHandler getTwittwrDirectMessageRecievedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTwitterRedirectUrl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTwitterRedirectUrl(string consumerKey, string consumerSecret, string CallBackUrl) {
            object[] results = this.Invoke("GetTwitterRedirectUrl", new object[] {
                        consumerKey,
                        consumerSecret,
                        CallBackUrl});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTwitterRedirectUrlAsync(string consumerKey, string consumerSecret, string CallBackUrl) {
            this.GetTwitterRedirectUrlAsync(consumerKey, consumerSecret, CallBackUrl, null);
        }
        
        /// <remarks/>
        public void GetTwitterRedirectUrlAsync(string consumerKey, string consumerSecret, string CallBackUrl, object userState) {
            if ((this.GetTwitterRedirectUrlOperationCompleted == null)) {
                this.GetTwitterRedirectUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTwitterRedirectUrlOperationCompleted);
            }
            this.InvokeAsync("GetTwitterRedirectUrl", new object[] {
                        consumerKey,
                        consumerSecret,
                        CallBackUrl}, this.GetTwitterRedirectUrlOperationCompleted, userState);
        }
        
        private void OnGetTwitterRedirectUrlOperationCompleted(object arg) {
            if ((this.GetTwitterRedirectUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTwitterRedirectUrlCompleted(this, new GetTwitterRedirectUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddTwitterAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddTwitterAccount(string client_id, string client_secret, string redirect_uri, string UserId, string GroupId, string requestToken, string requestSecret, string requestVerifier) {
            object[] results = this.Invoke("AddTwitterAccount", new object[] {
                        client_id,
                        client_secret,
                        redirect_uri,
                        UserId,
                        GroupId,
                        requestToken,
                        requestSecret,
                        requestVerifier});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddTwitterAccountAsync(string client_id, string client_secret, string redirect_uri, string UserId, string GroupId, string requestToken, string requestSecret, string requestVerifier) {
            this.AddTwitterAccountAsync(client_id, client_secret, redirect_uri, UserId, GroupId, requestToken, requestSecret, requestVerifier, null);
        }
        
        /// <remarks/>
        public void AddTwitterAccountAsync(string client_id, string client_secret, string redirect_uri, string UserId, string GroupId, string requestToken, string requestSecret, string requestVerifier, object userState) {
            if ((this.AddTwitterAccountOperationCompleted == null)) {
                this.AddTwitterAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddTwitterAccountOperationCompleted);
            }
            this.InvokeAsync("AddTwitterAccount", new object[] {
                        client_id,
                        client_secret,
                        redirect_uri,
                        UserId,
                        GroupId,
                        requestToken,
                        requestSecret,
                        requestVerifier}, this.AddTwitterAccountOperationCompleted, userState);
        }
        
        private void OnAddTwitterAccountOperationCompleted(object arg) {
            if ((this.AddTwitterAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddTwitterAccountCompleted(this, new AddTwitterAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TwitterLogIn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TwitterLogIn(string client_id, string client_secret, string redirect_uri, string requestToken, string requestSecret, string requestVerifier) {
            object[] results = this.Invoke("TwitterLogIn", new object[] {
                        client_id,
                        client_secret,
                        redirect_uri,
                        requestToken,
                        requestSecret,
                        requestVerifier});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TwitterLogInAsync(string client_id, string client_secret, string redirect_uri, string requestToken, string requestSecret, string requestVerifier) {
            this.TwitterLogInAsync(client_id, client_secret, redirect_uri, requestToken, requestSecret, requestVerifier, null);
        }
        
        /// <remarks/>
        public void TwitterLogInAsync(string client_id, string client_secret, string redirect_uri, string requestToken, string requestSecret, string requestVerifier, object userState) {
            if ((this.TwitterLogInOperationCompleted == null)) {
                this.TwitterLogInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTwitterLogInOperationCompleted);
            }
            this.InvokeAsync("TwitterLogIn", new object[] {
                        client_id,
                        client_secret,
                        redirect_uri,
                        requestToken,
                        requestSecret,
                        requestVerifier}, this.TwitterLogInOperationCompleted, userState);
        }
        
        private void OnTwitterLogInOperationCompleted(object arg) {
            if ((this.TwitterLogInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TwitterLogInCompleted(this, new TwitterLogInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTwitterFeeds", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getTwitterFeeds(string UserId, oAuthTwitter OAuth) {
            this.Invoke("getTwitterFeeds", new object[] {
                        UserId,
                        OAuth});
        }
        
        /// <remarks/>
        public void getTwitterFeedsAsync(string UserId, oAuthTwitter OAuth) {
            this.getTwitterFeedsAsync(UserId, OAuth, null);
        }
        
        /// <remarks/>
        public void getTwitterFeedsAsync(string UserId, oAuthTwitter OAuth, object userState) {
            if ((this.getTwitterFeedsOperationCompleted == null)) {
                this.getTwitterFeedsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTwitterFeedsOperationCompleted);
            }
            this.InvokeAsync("getTwitterFeeds", new object[] {
                        UserId,
                        OAuth}, this.getTwitterFeedsOperationCompleted, userState);
        }
        
        private void OngetTwitterFeedsOperationCompleted(object arg) {
            if ((this.getTwitterFeedsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTwitterFeedsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserRetweets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getUserRetweets(string UserId, oAuthTwitter OAuth) {
            this.Invoke("getUserRetweets", new object[] {
                        UserId,
                        OAuth});
        }
        
        /// <remarks/>
        public void getUserRetweetsAsync(string UserId, oAuthTwitter OAuth) {
            this.getUserRetweetsAsync(UserId, OAuth, null);
        }
        
        /// <remarks/>
        public void getUserRetweetsAsync(string UserId, oAuthTwitter OAuth, object userState) {
            if ((this.getUserRetweetsOperationCompleted == null)) {
                this.getUserRetweetsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserRetweetsOperationCompleted);
            }
            this.InvokeAsync("getUserRetweets", new object[] {
                        UserId,
                        OAuth}, this.getUserRetweetsOperationCompleted, userState);
        }
        
        private void OngetUserRetweetsOperationCompleted(object arg) {
            if ((this.getUserRetweetsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserRetweetsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTwitterMessages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getTwitterMessages(string UserId, oAuthTwitter OAuth) {
            this.Invoke("getTwitterMessages", new object[] {
                        UserId,
                        OAuth});
        }
        
        /// <remarks/>
        public void getTwitterMessagesAsync(string UserId, oAuthTwitter OAuth) {
            this.getTwitterMessagesAsync(UserId, OAuth, null);
        }
        
        /// <remarks/>
        public void getTwitterMessagesAsync(string UserId, oAuthTwitter OAuth, object userState) {
            if ((this.getTwitterMessagesOperationCompleted == null)) {
                this.getTwitterMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTwitterMessagesOperationCompleted);
            }
            this.InvokeAsync("getTwitterMessages", new object[] {
                        UserId,
                        OAuth}, this.getTwitterMessagesOperationCompleted, userState);
        }
        
        private void OngetTwitterMessagesOperationCompleted(object arg) {
            if ((this.getTwitterMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTwitterMessagesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTwitterData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getTwitterData(string UserId, string twitterid) {
            object[] results = this.Invoke("getTwitterData", new object[] {
                        UserId,
                        twitterid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTwitterDataAsync(string UserId, string twitterid) {
            this.getTwitterDataAsync(UserId, twitterid, null);
        }
        
        /// <remarks/>
        public void getTwitterDataAsync(string UserId, string twitterid, object userState) {
            if ((this.getTwitterDataOperationCompleted == null)) {
                this.getTwitterDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTwitterDataOperationCompleted);
            }
            this.InvokeAsync("getTwitterData", new object[] {
                        UserId,
                        twitterid}, this.getTwitterDataOperationCompleted, userState);
        }
        
        private void OngetTwitterDataOperationCompleted(object arg) {
            if ((this.getTwitterDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTwitterDataCompleted(this, new getTwitterDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SheduleTwitterMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SheduleTwitterMessage(string TwitterId, string UserId, string sscheduledmsgguid) {
            object[] results = this.Invoke("SheduleTwitterMessage", new object[] {
                        TwitterId,
                        UserId,
                        sscheduledmsgguid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SheduleTwitterMessageAsync(string TwitterId, string UserId, string sscheduledmsgguid) {
            this.SheduleTwitterMessageAsync(TwitterId, UserId, sscheduledmsgguid, null);
        }
        
        /// <remarks/>
        public void SheduleTwitterMessageAsync(string TwitterId, string UserId, string sscheduledmsgguid, object userState) {
            if ((this.SheduleTwitterMessageOperationCompleted == null)) {
                this.SheduleTwitterMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSheduleTwitterMessageOperationCompleted);
            }
            this.InvokeAsync("SheduleTwitterMessage", new object[] {
                        TwitterId,
                        UserId,
                        sscheduledmsgguid}, this.SheduleTwitterMessageOperationCompleted, userState);
        }
        
        private void OnSheduleTwitterMessageOperationCompleted(object arg) {
            if ((this.SheduleTwitterMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SheduleTwitterMessageCompleted(this, new SheduleTwitterMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserProile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getUserProile(oAuthTwitter OAuth, string TwitterScreenName, System.Guid userId) {
            this.Invoke("getUserProile", new object[] {
                        OAuth,
                        TwitterScreenName,
                        userId});
        }
        
        /// <remarks/>
        public void getUserProileAsync(oAuthTwitter OAuth, string TwitterScreenName, System.Guid userId) {
            this.getUserProileAsync(OAuth, TwitterScreenName, userId, null);
        }
        
        /// <remarks/>
        public void getUserProileAsync(oAuthTwitter OAuth, string TwitterScreenName, System.Guid userId, object userState) {
            if ((this.getUserProileOperationCompleted == null)) {
                this.getUserProileOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserProileOperationCompleted);
            }
            this.InvokeAsync("getUserProile", new object[] {
                        OAuth,
                        TwitterScreenName,
                        userId}, this.getUserProileOperationCompleted, userState);
        }
        
        private void OngetUserProileOperationCompleted(object arg) {
            if ((this.getUserProileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserProileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserTweets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getUserTweets(oAuthTwitter OAuth, string TwitterScreenName, string TwitterUserId, System.Guid userId, TwitterAccount objTwitterAccount) {
            this.Invoke("getUserTweets", new object[] {
                        OAuth,
                        TwitterScreenName,
                        TwitterUserId,
                        userId,
                        objTwitterAccount});
        }
        
        /// <remarks/>
        public void getUserTweetsAsync(oAuthTwitter OAuth, string TwitterScreenName, string TwitterUserId, System.Guid userId, TwitterAccount objTwitterAccount) {
            this.getUserTweetsAsync(OAuth, TwitterScreenName, TwitterUserId, userId, objTwitterAccount, null);
        }
        
        /// <remarks/>
        public void getUserTweetsAsync(oAuthTwitter OAuth, string TwitterScreenName, string TwitterUserId, System.Guid userId, TwitterAccount objTwitterAccount, object userState) {
            if ((this.getUserTweetsOperationCompleted == null)) {
                this.getUserTweetsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserTweetsOperationCompleted);
            }
            this.InvokeAsync("getUserTweets", new object[] {
                        OAuth,
                        TwitterScreenName,
                        TwitterUserId,
                        userId,
                        objTwitterAccount}, this.getUserTweetsOperationCompleted, userState);
        }
        
        private void OngetUserTweetsOperationCompleted(object arg) {
            if ((this.getUserTweetsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserTweetsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserFeed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getUserFeed(oAuthTwitter OAuth, string TwitterScreenName, string TwitterUserId, System.Guid userId) {
            this.Invoke("getUserFeed", new object[] {
                        OAuth,
                        TwitterScreenName,
                        TwitterUserId,
                        userId});
        }
        
        /// <remarks/>
        public void getUserFeedAsync(oAuthTwitter OAuth, string TwitterScreenName, string TwitterUserId, System.Guid userId) {
            this.getUserFeedAsync(OAuth, TwitterScreenName, TwitterUserId, userId, null);
        }
        
        /// <remarks/>
        public void getUserFeedAsync(oAuthTwitter OAuth, string TwitterScreenName, string TwitterUserId, System.Guid userId, object userState) {
            if ((this.getUserFeedOperationCompleted == null)) {
                this.getUserFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserFeedOperationCompleted);
            }
            this.InvokeAsync("getUserFeed", new object[] {
                        OAuth,
                        TwitterScreenName,
                        TwitterUserId,
                        userId}, this.getUserFeedOperationCompleted, userState);
        }
        
        private void OngetUserFeedOperationCompleted(object arg) {
            if ((this.getUserFeedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserFeedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TwitterComposeMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TwitterComposeMessage(string message, string profileid, string userid, string currentdatetime, string picurl) {
            object[] results = this.Invoke("TwitterComposeMessage", new object[] {
                        message,
                        profileid,
                        userid,
                        currentdatetime,
                        picurl});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TwitterComposeMessageAsync(string message, string profileid, string userid, string currentdatetime, string picurl) {
            this.TwitterComposeMessageAsync(message, profileid, userid, currentdatetime, picurl, null);
        }
        
        /// <remarks/>
        public void TwitterComposeMessageAsync(string message, string profileid, string userid, string currentdatetime, string picurl, object userState) {
            if ((this.TwitterComposeMessageOperationCompleted == null)) {
                this.TwitterComposeMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTwitterComposeMessageOperationCompleted);
            }
            this.InvokeAsync("TwitterComposeMessage", new object[] {
                        message,
                        profileid,
                        userid,
                        currentdatetime,
                        picurl}, this.TwitterComposeMessageOperationCompleted, userState);
        }
        
        private void OnTwitterComposeMessageOperationCompleted(object arg) {
            if ((this.TwitterComposeMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TwitterComposeMessageCompleted(this, new TwitterComposeMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TwitterComposeMessageRss", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TwitterComposeMessageRss(string message, string profileid, string userid) {
            object[] results = this.Invoke("TwitterComposeMessageRss", new object[] {
                        message,
                        profileid,
                        userid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TwitterComposeMessageRssAsync(string message, string profileid, string userid) {
            this.TwitterComposeMessageRssAsync(message, profileid, userid, null);
        }
        
        /// <remarks/>
        public void TwitterComposeMessageRssAsync(string message, string profileid, string userid, object userState) {
            if ((this.TwitterComposeMessageRssOperationCompleted == null)) {
                this.TwitterComposeMessageRssOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTwitterComposeMessageRssOperationCompleted);
            }
            this.InvokeAsync("TwitterComposeMessageRss", new object[] {
                        message,
                        profileid,
                        userid}, this.TwitterComposeMessageRssOperationCompleted, userState);
        }
        
        private void OnTwitterComposeMessageRssOperationCompleted(object arg) {
            if ((this.TwitterComposeMessageRssCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TwitterComposeMessageRssCompleted(this, new TwitterComposeMessageRssCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TwitterRecentFollower", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TwitterRecentFollower(string userid) {
            object[] results = this.Invoke("TwitterRecentFollower", new object[] {
                        userid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TwitterRecentFollowerAsync(string userid) {
            this.TwitterRecentFollowerAsync(userid, null);
        }
        
        /// <remarks/>
        public void TwitterRecentFollowerAsync(string userid, object userState) {
            if ((this.TwitterRecentFollowerOperationCompleted == null)) {
                this.TwitterRecentFollowerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTwitterRecentFollowerOperationCompleted);
            }
            this.InvokeAsync("TwitterRecentFollower", new object[] {
                        userid}, this.TwitterRecentFollowerOperationCompleted, userState);
        }
        
        private void OnTwitterRecentFollowerOperationCompleted(object arg) {
            if ((this.TwitterRecentFollowerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TwitterRecentFollowerCompleted(this, new TwitterRecentFollowerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TwitterReplyUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TwitterReplyUpdate(string message, string userid, string profileid, string statusid) {
            object[] results = this.Invoke("TwitterReplyUpdate", new object[] {
                        message,
                        userid,
                        profileid,
                        statusid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TwitterReplyUpdateAsync(string message, string userid, string profileid, string statusid) {
            this.TwitterReplyUpdateAsync(message, userid, profileid, statusid, null);
        }
        
        /// <remarks/>
        public void TwitterReplyUpdateAsync(string message, string userid, string profileid, string statusid, object userState) {
            if ((this.TwitterReplyUpdateOperationCompleted == null)) {
                this.TwitterReplyUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTwitterReplyUpdateOperationCompleted);
            }
            this.InvokeAsync("TwitterReplyUpdate", new object[] {
                        message,
                        userid,
                        profileid,
                        statusid}, this.TwitterReplyUpdateOperationCompleted, userState);
        }
        
        private void OnTwitterReplyUpdateOperationCompleted(object arg) {
            if ((this.TwitterReplyUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TwitterReplyUpdateCompleted(this, new TwitterReplyUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TwitterReteet_post", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TwitterReteet_post(string userid, string profileid, string messageid) {
            object[] results = this.Invoke("TwitterReteet_post", new object[] {
                        userid,
                        profileid,
                        messageid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TwitterReteet_postAsync(string userid, string profileid, string messageid) {
            this.TwitterReteet_postAsync(userid, profileid, messageid, null);
        }
        
        /// <remarks/>
        public void TwitterReteet_postAsync(string userid, string profileid, string messageid, object userState) {
            if ((this.TwitterReteet_postOperationCompleted == null)) {
                this.TwitterReteet_postOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTwitterReteet_postOperationCompleted);
            }
            this.InvokeAsync("TwitterReteet_post", new object[] {
                        userid,
                        profileid,
                        messageid}, this.TwitterReteet_postOperationCompleted, userState);
        }
        
        private void OnTwitterReteet_postOperationCompleted(object arg) {
            if ((this.TwitterReteet_postCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TwitterReteet_postCompleted(this, new TwitterReteet_postCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TwitterFavorite_post", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TwitterFavorite_post(string userid, string profileid, string messageid) {
            object[] results = this.Invoke("TwitterFavorite_post", new object[] {
                        userid,
                        profileid,
                        messageid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TwitterFavorite_postAsync(string userid, string profileid, string messageid) {
            this.TwitterFavorite_postAsync(userid, profileid, messageid, null);
        }
        
        /// <remarks/>
        public void TwitterFavorite_postAsync(string userid, string profileid, string messageid, object userState) {
            if ((this.TwitterFavorite_postOperationCompleted == null)) {
                this.TwitterFavorite_postOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTwitterFavorite_postOperationCompleted);
            }
            this.InvokeAsync("TwitterFavorite_post", new object[] {
                        userid,
                        profileid,
                        messageid}, this.TwitterFavorite_postOperationCompleted, userState);
        }
        
        private void OnTwitterFavorite_postOperationCompleted(object arg) {
            if ((this.TwitterFavorite_postCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TwitterFavorite_postCompleted(this, new TwitterFavorite_postCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SpamUser_post", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SpamUser_post(string userid, string SpammerScreanName, string UserProfileId) {
            object[] results = this.Invoke("SpamUser_post", new object[] {
                        userid,
                        SpammerScreanName,
                        UserProfileId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SpamUser_postAsync(string userid, string SpammerScreanName, string UserProfileId) {
            this.SpamUser_postAsync(userid, SpammerScreanName, UserProfileId, null);
        }
        
        /// <remarks/>
        public void SpamUser_postAsync(string userid, string SpammerScreanName, string UserProfileId, object userState) {
            if ((this.SpamUser_postOperationCompleted == null)) {
                this.SpamUser_postOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSpamUser_postOperationCompleted);
            }
            this.InvokeAsync("SpamUser_post", new object[] {
                        userid,
                        SpammerScreanName,
                        UserProfileId}, this.SpamUser_postOperationCompleted, userState);
        }
        
        private void OnSpamUser_postOperationCompleted(object arg) {
            if ((this.SpamUser_postCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SpamUser_postCompleted(this, new SpamUser_postCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TwitterProfileDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TwitterProfileDetails(string userid, string profileid) {
            object[] results = this.Invoke("TwitterProfileDetails", new object[] {
                        userid,
                        profileid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TwitterProfileDetailsAsync(string userid, string profileid) {
            this.TwitterProfileDetailsAsync(userid, profileid, null);
        }
        
        /// <remarks/>
        public void TwitterProfileDetailsAsync(string userid, string profileid, object userState) {
            if ((this.TwitterProfileDetailsOperationCompleted == null)) {
                this.TwitterProfileDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTwitterProfileDetailsOperationCompleted);
            }
            this.InvokeAsync("TwitterProfileDetails", new object[] {
                        userid,
                        profileid}, this.TwitterProfileDetailsOperationCompleted, userState);
        }
        
        private void OnTwitterProfileDetailsOperationCompleted(object arg) {
            if ((this.TwitterProfileDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TwitterProfileDetailsCompleted(this, new TwitterProfileDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateTwitterAccountByAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateTwitterAccountByAdmin(string ObjTwitter) {
            object[] results = this.Invoke("UpdateTwitterAccountByAdmin", new object[] {
                        ObjTwitter});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTwitterAccountByAdminAsync(string ObjTwitter) {
            this.UpdateTwitterAccountByAdminAsync(ObjTwitter, null);
        }
        
        /// <remarks/>
        public void UpdateTwitterAccountByAdminAsync(string ObjTwitter, object userState) {
            if ((this.UpdateTwitterAccountByAdminOperationCompleted == null)) {
                this.UpdateTwitterAccountByAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTwitterAccountByAdminOperationCompleted);
            }
            this.InvokeAsync("UpdateTwitterAccountByAdmin", new object[] {
                        ObjTwitter}, this.UpdateTwitterAccountByAdminOperationCompleted, userState);
        }
        
        private void OnUpdateTwitterAccountByAdminOperationCompleted(object arg) {
            if ((this.UpdateTwitterAccountByAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTwitterAccountByAdminCompleted(this, new UpdateTwitterAccountByAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TicketTwitterReply", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TicketTwitterReply(string message, string profileid, string statusid) {
            object[] results = this.Invoke("TicketTwitterReply", new object[] {
                        message,
                        profileid,
                        statusid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TicketTwitterReplyAsync(string message, string profileid, string statusid) {
            this.TicketTwitterReplyAsync(message, profileid, statusid, null);
        }
        
        /// <remarks/>
        public void TicketTwitterReplyAsync(string message, string profileid, string statusid, object userState) {
            if ((this.TicketTwitterReplyOperationCompleted == null)) {
                this.TicketTwitterReplyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTicketTwitterReplyOperationCompleted);
            }
            this.InvokeAsync("TicketTwitterReply", new object[] {
                        message,
                        profileid,
                        statusid}, this.TicketTwitterReplyOperationCompleted, userState);
        }
        
        private void OnTicketTwitterReplyOperationCompleted(object arg) {
            if ((this.TicketTwitterReplyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TicketTwitterReplyCompleted(this, new TicketTwitterReplyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserMentions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getUserMentions(oAuthTwitter OAuth, string TwitterUserId, System.Guid userId) {
            this.Invoke("getUserMentions", new object[] {
                        OAuth,
                        TwitterUserId,
                        userId});
        }
        
        /// <remarks/>
        public void getUserMentionsAsync(oAuthTwitter OAuth, string TwitterUserId, System.Guid userId) {
            this.getUserMentionsAsync(OAuth, TwitterUserId, userId, null);
        }
        
        /// <remarks/>
        public void getUserMentionsAsync(oAuthTwitter OAuth, string TwitterUserId, System.Guid userId, object userState) {
            if ((this.getUserMentionsOperationCompleted == null)) {
                this.getUserMentionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserMentionsOperationCompleted);
            }
            this.InvokeAsync("getUserMentions", new object[] {
                        OAuth,
                        TwitterUserId,
                        userId}, this.getUserMentionsOperationCompleted, userState);
        }
        
        private void OngetUserMentionsOperationCompleted(object arg) {
            if ((this.getUserMentionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserMentionsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserFollowers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getUserFollowers(oAuthTwitter OAuth, string screeenName, string TwitterUserId, System.Guid userId) {
            this.Invoke("getUserFollowers", new object[] {
                        OAuth,
                        screeenName,
                        TwitterUserId,
                        userId});
        }
        
        /// <remarks/>
        public void getUserFollowersAsync(oAuthTwitter OAuth, string screeenName, string TwitterUserId, System.Guid userId) {
            this.getUserFollowersAsync(OAuth, screeenName, TwitterUserId, userId, null);
        }
        
        /// <remarks/>
        public void getUserFollowersAsync(oAuthTwitter OAuth, string screeenName, string TwitterUserId, System.Guid userId, object userState) {
            if ((this.getUserFollowersOperationCompleted == null)) {
                this.getUserFollowersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserFollowersOperationCompleted);
            }
            this.InvokeAsync("getUserFollowers", new object[] {
                        OAuth,
                        screeenName,
                        TwitterUserId,
                        userId}, this.getUserFollowersOperationCompleted, userState);
        }
        
        private void OngetUserFollowersOperationCompleted(object arg) {
            if ((this.getUserFollowersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserFollowersCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserRetweet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getUserRetweet(oAuthTwitter OAuth, string TwitterUserId, System.Guid userId) {
            this.Invoke("getUserRetweet", new object[] {
                        OAuth,
                        TwitterUserId,
                        userId});
        }
        
        /// <remarks/>
        public void getUserRetweetAsync(oAuthTwitter OAuth, string TwitterUserId, System.Guid userId) {
            this.getUserRetweetAsync(OAuth, TwitterUserId, userId, null);
        }
        
        /// <remarks/>
        public void getUserRetweetAsync(oAuthTwitter OAuth, string TwitterUserId, System.Guid userId, object userState) {
            if ((this.getUserRetweetOperationCompleted == null)) {
                this.getUserRetweetOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserRetweetOperationCompleted);
            }
            this.InvokeAsync("getUserRetweet", new object[] {
                        OAuth,
                        TwitterUserId,
                        userId}, this.getUserRetweetOperationCompleted, userState);
        }
        
        private void OngetUserRetweetOperationCompleted(object arg) {
            if ((this.getUserRetweetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserRetweetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserFollowersData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getUserFollowersData(oAuthTwitter OAuth, string screeenName, string TwitterUserId, System.Guid userId) {
            this.Invoke("getUserFollowersData", new object[] {
                        OAuth,
                        screeenName,
                        TwitterUserId,
                        userId});
        }
        
        /// <remarks/>
        public void getUserFollowersDataAsync(oAuthTwitter OAuth, string screeenName, string TwitterUserId, System.Guid userId) {
            this.getUserFollowersDataAsync(OAuth, screeenName, TwitterUserId, userId, null);
        }
        
        /// <remarks/>
        public void getUserFollowersDataAsync(oAuthTwitter OAuth, string screeenName, string TwitterUserId, System.Guid userId, object userState) {
            if ((this.getUserFollowersDataOperationCompleted == null)) {
                this.getUserFollowersDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserFollowersDataOperationCompleted);
            }
            this.InvokeAsync("getUserFollowersData", new object[] {
                        OAuth,
                        screeenName,
                        TwitterUserId,
                        userId}, this.getUserFollowersDataOperationCompleted, userState);
        }
        
        private void OngetUserFollowersDataOperationCompleted(object arg) {
            if ((this.getUserFollowersDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserFollowersDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTwitterDirectMessageSent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getTwitterDirectMessageSent(string UserId, oAuthTwitter OAuth) {
            this.Invoke("getTwitterDirectMessageSent", new object[] {
                        UserId,
                        OAuth});
        }
        
        /// <remarks/>
        public void getTwitterDirectMessageSentAsync(string UserId, oAuthTwitter OAuth) {
            this.getTwitterDirectMessageSentAsync(UserId, OAuth, null);
        }
        
        /// <remarks/>
        public void getTwitterDirectMessageSentAsync(string UserId, oAuthTwitter OAuth, object userState) {
            if ((this.getTwitterDirectMessageSentOperationCompleted == null)) {
                this.getTwitterDirectMessageSentOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTwitterDirectMessageSentOperationCompleted);
            }
            this.InvokeAsync("getTwitterDirectMessageSent", new object[] {
                        UserId,
                        OAuth}, this.getTwitterDirectMessageSentOperationCompleted, userState);
        }
        
        private void OngetTwitterDirectMessageSentOperationCompleted(object arg) {
            if ((this.getTwitterDirectMessageSentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTwitterDirectMessageSentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTwittwrDirectMessageRecieved", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getTwittwrDirectMessageRecieved(oAuthTwitter OAuth, string UserId) {
            this.Invoke("getTwittwrDirectMessageRecieved", new object[] {
                        OAuth,
                        UserId});
        }
        
        /// <remarks/>
        public void getTwittwrDirectMessageRecievedAsync(oAuthTwitter OAuth, string UserId) {
            this.getTwittwrDirectMessageRecievedAsync(OAuth, UserId, null);
        }
        
        /// <remarks/>
        public void getTwittwrDirectMessageRecievedAsync(oAuthTwitter OAuth, string UserId, object userState) {
            if ((this.getTwittwrDirectMessageRecievedOperationCompleted == null)) {
                this.getTwittwrDirectMessageRecievedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTwittwrDirectMessageRecievedOperationCompleted);
            }
            this.InvokeAsync("getTwittwrDirectMessageRecieved", new object[] {
                        OAuth,
                        UserId}, this.getTwittwrDirectMessageRecievedOperationCompleted, userState);
        }
        
        private void OngetTwittwrDirectMessageRecievedOperationCompleted(object arg) {
            if ((this.getTwittwrDirectMessageRecievedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTwittwrDirectMessageRecievedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class oAuthTwitter : OAuthBase {
        
        private string callBackUrlField;
        
        private string consumerKeyField;
        
        private string consumerKeySecretField;
        
        private string accessTokenField;
        
        private string accessTokenSecretField;
        
        private string oAuthVeriferField;
        
        private string twitterScreenNameField;
        
        private string profileImageField;
        
        private string twitterUserIdField;
        
        /// <remarks/>
        public string CallBackUrl {
            get {
                return this.callBackUrlField;
            }
            set {
                this.callBackUrlField = value;
            }
        }
        
        /// <remarks/>
        public string ConsumerKey {
            get {
                return this.consumerKeyField;
            }
            set {
                this.consumerKeyField = value;
            }
        }
        
        /// <remarks/>
        public string ConsumerKeySecret {
            get {
                return this.consumerKeySecretField;
            }
            set {
                this.consumerKeySecretField = value;
            }
        }
        
        /// <remarks/>
        public string AccessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
            }
        }
        
        /// <remarks/>
        public string AccessTokenSecret {
            get {
                return this.accessTokenSecretField;
            }
            set {
                this.accessTokenSecretField = value;
            }
        }
        
        /// <remarks/>
        public string OAuthVerifer {
            get {
                return this.oAuthVeriferField;
            }
            set {
                this.oAuthVeriferField = value;
            }
        }
        
        /// <remarks/>
        public string TwitterScreenName {
            get {
                return this.twitterScreenNameField;
            }
            set {
                this.twitterScreenNameField = value;
            }
        }
        
        /// <remarks/>
        public string ProfileImage {
            get {
                return this.profileImageField;
            }
            set {
                this.profileImageField = value;
            }
        }
        
        /// <remarks/>
        public string TwitterUserId {
            get {
                return this.twitterUserIdField;
            }
            set {
                this.twitterUserIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(oAuthTwitter))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OAuthBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TwitterAccount {
        
        private System.Guid idField;
        
        private string twitterUserIdField;
        
        private string twitterScreenNameField;
        
        private string oAuthTokenField;
        
        private string oAuthSecretField;
        
        private System.Guid userIdField;
        
        private int followersCountField;
        
        private bool isActiveField;
        
        private int followingCountField;
        
        private string profileUrlField;
        
        private string profileImageUrlField;
        
        private string twitterNameField;
        
        private string profileTypeField;
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string TwitterUserId {
            get {
                return this.twitterUserIdField;
            }
            set {
                this.twitterUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string TwitterScreenName {
            get {
                return this.twitterScreenNameField;
            }
            set {
                this.twitterScreenNameField = value;
            }
        }
        
        /// <remarks/>
        public string OAuthToken {
            get {
                return this.oAuthTokenField;
            }
            set {
                this.oAuthTokenField = value;
            }
        }
        
        /// <remarks/>
        public string OAuthSecret {
            get {
                return this.oAuthSecretField;
            }
            set {
                this.oAuthSecretField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public int FollowersCount {
            get {
                return this.followersCountField;
            }
            set {
                this.followersCountField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public int FollowingCount {
            get {
                return this.followingCountField;
            }
            set {
                this.followingCountField = value;
            }
        }
        
        /// <remarks/>
        public string ProfileUrl {
            get {
                return this.profileUrlField;
            }
            set {
                this.profileUrlField = value;
            }
        }
        
        /// <remarks/>
        public string ProfileImageUrl {
            get {
                return this.profileImageUrlField;
            }
            set {
                this.profileImageUrlField = value;
            }
        }
        
        /// <remarks/>
        public string TwitterName {
            get {
                return this.twitterNameField;
            }
            set {
                this.twitterNameField = value;
            }
        }
        
        /// <remarks/>
        public string ProfileType {
            get {
                return this.profileTypeField;
            }
            set {
                this.profileTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetTwitterRedirectUrlCompletedEventHandler(object sender, GetTwitterRedirectUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTwitterRedirectUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTwitterRedirectUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AddTwitterAccountCompletedEventHandler(object sender, AddTwitterAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddTwitterAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddTwitterAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TwitterLogInCompletedEventHandler(object sender, TwitterLogInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwitterLogInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TwitterLogInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getTwitterFeedsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getUserRetweetsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getTwitterMessagesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getTwitterDataCompletedEventHandler(object sender, getTwitterDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTwitterDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTwitterDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SheduleTwitterMessageCompletedEventHandler(object sender, SheduleTwitterMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SheduleTwitterMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SheduleTwitterMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getUserProileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getUserTweetsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getUserFeedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TwitterComposeMessageCompletedEventHandler(object sender, TwitterComposeMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwitterComposeMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TwitterComposeMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TwitterComposeMessageRssCompletedEventHandler(object sender, TwitterComposeMessageRssCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwitterComposeMessageRssCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TwitterComposeMessageRssCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TwitterRecentFollowerCompletedEventHandler(object sender, TwitterRecentFollowerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwitterRecentFollowerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TwitterRecentFollowerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TwitterReplyUpdateCompletedEventHandler(object sender, TwitterReplyUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwitterReplyUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TwitterReplyUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TwitterReteet_postCompletedEventHandler(object sender, TwitterReteet_postCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwitterReteet_postCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TwitterReteet_postCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TwitterFavorite_postCompletedEventHandler(object sender, TwitterFavorite_postCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwitterFavorite_postCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TwitterFavorite_postCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SpamUser_postCompletedEventHandler(object sender, SpamUser_postCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SpamUser_postCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SpamUser_postCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TwitterProfileDetailsCompletedEventHandler(object sender, TwitterProfileDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwitterProfileDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TwitterProfileDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UpdateTwitterAccountByAdminCompletedEventHandler(object sender, UpdateTwitterAccountByAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTwitterAccountByAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTwitterAccountByAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TicketTwitterReplyCompletedEventHandler(object sender, TicketTwitterReplyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TicketTwitterReplyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TicketTwitterReplyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getUserMentionsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getUserFollowersCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getUserRetweetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getUserFollowersDataCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getTwitterDirectMessageSentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getTwittwrDirectMessageRecievedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591