//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Socioboard.Api.FacebookMessage {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FacebookMessageSoap", Namespace="http://tempuri.org/")]
    public partial class FacebookMessage : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UserHomeWithLimitOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserHomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllFacebookMessagesOfUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllSentMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllWallpostsOfProfileAccordingtoGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllFacebookMessagesOfUserByProfileIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllFacebookTagOfUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllFacebookstatusOfUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllFacebookUserFeedOfUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageDetailByMessageidOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FacebookMessage() {
            this.Url = global::Socioboard.Properties.Settings.Default.Socioboard_Api_FacebookMessage_FacebookMessage;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UserHomeWithLimitCompletedEventHandler UserHomeWithLimitCompleted;
        
        /// <remarks/>
        public event UserHomeCompletedEventHandler UserHomeCompleted;
        
        /// <remarks/>
        public event getAllFacebookMessagesOfUserCompletedEventHandler getAllFacebookMessagesOfUserCompleted;
        
        /// <remarks/>
        public event getAllSentMessagesCompletedEventHandler getAllSentMessagesCompleted;
        
        /// <remarks/>
        public event GetAllWallpostsOfProfileAccordingtoGroupCompletedEventHandler GetAllWallpostsOfProfileAccordingtoGroupCompleted;
        
        /// <remarks/>
        public event getAllFacebookMessagesOfUserByProfileIdCompletedEventHandler getAllFacebookMessagesOfUserByProfileIdCompleted;
        
        /// <remarks/>
        public event getAllFacebookTagOfUsersCompletedEventHandler getAllFacebookTagOfUsersCompleted;
        
        /// <remarks/>
        public event getAllFacebookstatusOfUsersCompletedEventHandler getAllFacebookstatusOfUsersCompleted;
        
        /// <remarks/>
        public event getAllFacebookUserFeedOfUsersCompletedEventHandler getAllFacebookUserFeedOfUsersCompleted;
        
        /// <remarks/>
        public event GetMessageDetailByMessageidCompletedEventHandler GetMessageDetailByMessageidCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserHomeWithLimit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UserHomeWithLimit(string UserId, string FacebookId, string count) {
            object[] results = this.Invoke("UserHomeWithLimit", new object[] {
                        UserId,
                        FacebookId,
                        count});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UserHomeWithLimitAsync(string UserId, string FacebookId, string count) {
            this.UserHomeWithLimitAsync(UserId, FacebookId, count, null);
        }
        
        /// <remarks/>
        public void UserHomeWithLimitAsync(string UserId, string FacebookId, string count, object userState) {
            if ((this.UserHomeWithLimitOperationCompleted == null)) {
                this.UserHomeWithLimitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserHomeWithLimitOperationCompleted);
            }
            this.InvokeAsync("UserHomeWithLimit", new object[] {
                        UserId,
                        FacebookId,
                        count}, this.UserHomeWithLimitOperationCompleted, userState);
        }
        
        private void OnUserHomeWithLimitOperationCompleted(object arg) {
            if ((this.UserHomeWithLimitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserHomeWithLimitCompleted(this, new UserHomeWithLimitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserHome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UserHome(string UserId, string FacebookId) {
            object[] results = this.Invoke("UserHome", new object[] {
                        UserId,
                        FacebookId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UserHomeAsync(string UserId, string FacebookId) {
            this.UserHomeAsync(UserId, FacebookId, null);
        }
        
        /// <remarks/>
        public void UserHomeAsync(string UserId, string FacebookId, object userState) {
            if ((this.UserHomeOperationCompleted == null)) {
                this.UserHomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserHomeOperationCompleted);
            }
            this.InvokeAsync("UserHome", new object[] {
                        UserId,
                        FacebookId}, this.UserHomeOperationCompleted, userState);
        }
        
        private void OnUserHomeOperationCompleted(object arg) {
            if ((this.UserHomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserHomeCompleted(this, new UserHomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllFacebookMessagesOfUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAllFacebookMessagesOfUser(string UserId, string ProfileId) {
            object[] results = this.Invoke("getAllFacebookMessagesOfUser", new object[] {
                        UserId,
                        ProfileId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAllFacebookMessagesOfUserAsync(string UserId, string ProfileId) {
            this.getAllFacebookMessagesOfUserAsync(UserId, ProfileId, null);
        }
        
        /// <remarks/>
        public void getAllFacebookMessagesOfUserAsync(string UserId, string ProfileId, object userState) {
            if ((this.getAllFacebookMessagesOfUserOperationCompleted == null)) {
                this.getAllFacebookMessagesOfUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllFacebookMessagesOfUserOperationCompleted);
            }
            this.InvokeAsync("getAllFacebookMessagesOfUser", new object[] {
                        UserId,
                        ProfileId}, this.getAllFacebookMessagesOfUserOperationCompleted, userState);
        }
        
        private void OngetAllFacebookMessagesOfUserOperationCompleted(object arg) {
            if ((this.getAllFacebookMessagesOfUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllFacebookMessagesOfUserCompleted(this, new getAllFacebookMessagesOfUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllSentMessages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAllSentMessages(string ProfileId) {
            object[] results = this.Invoke("getAllSentMessages", new object[] {
                        ProfileId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAllSentMessagesAsync(string ProfileId) {
            this.getAllSentMessagesAsync(ProfileId, null);
        }
        
        /// <remarks/>
        public void getAllSentMessagesAsync(string ProfileId, object userState) {
            if ((this.getAllSentMessagesOperationCompleted == null)) {
                this.getAllSentMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllSentMessagesOperationCompleted);
            }
            this.InvokeAsync("getAllSentMessages", new object[] {
                        ProfileId}, this.getAllSentMessagesOperationCompleted, userState);
        }
        
        private void OngetAllSentMessagesOperationCompleted(object arg) {
            if ((this.getAllSentMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllSentMessagesCompleted(this, new getAllSentMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllWallpostsOfProfileAccordingtoGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAllWallpostsOfProfileAccordingtoGroup(string profileid, int count, string UserId) {
            object[] results = this.Invoke("GetAllWallpostsOfProfileAccordingtoGroup", new object[] {
                        profileid,
                        count,
                        UserId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllWallpostsOfProfileAccordingtoGroupAsync(string profileid, int count, string UserId) {
            this.GetAllWallpostsOfProfileAccordingtoGroupAsync(profileid, count, UserId, null);
        }
        
        /// <remarks/>
        public void GetAllWallpostsOfProfileAccordingtoGroupAsync(string profileid, int count, string UserId, object userState) {
            if ((this.GetAllWallpostsOfProfileAccordingtoGroupOperationCompleted == null)) {
                this.GetAllWallpostsOfProfileAccordingtoGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllWallpostsOfProfileAccordingtoGroupOperationCompleted);
            }
            this.InvokeAsync("GetAllWallpostsOfProfileAccordingtoGroup", new object[] {
                        profileid,
                        count,
                        UserId}, this.GetAllWallpostsOfProfileAccordingtoGroupOperationCompleted, userState);
        }
        
        private void OnGetAllWallpostsOfProfileAccordingtoGroupOperationCompleted(object arg) {
            if ((this.GetAllWallpostsOfProfileAccordingtoGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllWallpostsOfProfileAccordingtoGroupCompleted(this, new GetAllWallpostsOfProfileAccordingtoGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllFacebookMessagesOfUserByProfileId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAllFacebookMessagesOfUserByProfileId(string ProfileId) {
            object[] results = this.Invoke("getAllFacebookMessagesOfUserByProfileId", new object[] {
                        ProfileId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAllFacebookMessagesOfUserByProfileIdAsync(string ProfileId) {
            this.getAllFacebookMessagesOfUserByProfileIdAsync(ProfileId, null);
        }
        
        /// <remarks/>
        public void getAllFacebookMessagesOfUserByProfileIdAsync(string ProfileId, object userState) {
            if ((this.getAllFacebookMessagesOfUserByProfileIdOperationCompleted == null)) {
                this.getAllFacebookMessagesOfUserByProfileIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllFacebookMessagesOfUserByProfileIdOperationCompleted);
            }
            this.InvokeAsync("getAllFacebookMessagesOfUserByProfileId", new object[] {
                        ProfileId}, this.getAllFacebookMessagesOfUserByProfileIdOperationCompleted, userState);
        }
        
        private void OngetAllFacebookMessagesOfUserByProfileIdOperationCompleted(object arg) {
            if ((this.getAllFacebookMessagesOfUserByProfileIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllFacebookMessagesOfUserByProfileIdCompleted(this, new getAllFacebookMessagesOfUserByProfileIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllFacebookTagOfUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAllFacebookTagOfUsers(string UserId, string ProfileId) {
            object[] results = this.Invoke("getAllFacebookTagOfUsers", new object[] {
                        UserId,
                        ProfileId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAllFacebookTagOfUsersAsync(string UserId, string ProfileId) {
            this.getAllFacebookTagOfUsersAsync(UserId, ProfileId, null);
        }
        
        /// <remarks/>
        public void getAllFacebookTagOfUsersAsync(string UserId, string ProfileId, object userState) {
            if ((this.getAllFacebookTagOfUsersOperationCompleted == null)) {
                this.getAllFacebookTagOfUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllFacebookTagOfUsersOperationCompleted);
            }
            this.InvokeAsync("getAllFacebookTagOfUsers", new object[] {
                        UserId,
                        ProfileId}, this.getAllFacebookTagOfUsersOperationCompleted, userState);
        }
        
        private void OngetAllFacebookTagOfUsersOperationCompleted(object arg) {
            if ((this.getAllFacebookTagOfUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllFacebookTagOfUsersCompleted(this, new getAllFacebookTagOfUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllFacebookstatusOfUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAllFacebookstatusOfUsers(string UserId, string ProfileId) {
            object[] results = this.Invoke("getAllFacebookstatusOfUsers", new object[] {
                        UserId,
                        ProfileId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAllFacebookstatusOfUsersAsync(string UserId, string ProfileId) {
            this.getAllFacebookstatusOfUsersAsync(UserId, ProfileId, null);
        }
        
        /// <remarks/>
        public void getAllFacebookstatusOfUsersAsync(string UserId, string ProfileId, object userState) {
            if ((this.getAllFacebookstatusOfUsersOperationCompleted == null)) {
                this.getAllFacebookstatusOfUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllFacebookstatusOfUsersOperationCompleted);
            }
            this.InvokeAsync("getAllFacebookstatusOfUsers", new object[] {
                        UserId,
                        ProfileId}, this.getAllFacebookstatusOfUsersOperationCompleted, userState);
        }
        
        private void OngetAllFacebookstatusOfUsersOperationCompleted(object arg) {
            if ((this.getAllFacebookstatusOfUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllFacebookstatusOfUsersCompleted(this, new getAllFacebookstatusOfUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllFacebookUserFeedOfUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAllFacebookUserFeedOfUsers(string UserId, string ProfileId) {
            object[] results = this.Invoke("getAllFacebookUserFeedOfUsers", new object[] {
                        UserId,
                        ProfileId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAllFacebookUserFeedOfUsersAsync(string UserId, string ProfileId) {
            this.getAllFacebookUserFeedOfUsersAsync(UserId, ProfileId, null);
        }
        
        /// <remarks/>
        public void getAllFacebookUserFeedOfUsersAsync(string UserId, string ProfileId, object userState) {
            if ((this.getAllFacebookUserFeedOfUsersOperationCompleted == null)) {
                this.getAllFacebookUserFeedOfUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllFacebookUserFeedOfUsersOperationCompleted);
            }
            this.InvokeAsync("getAllFacebookUserFeedOfUsers", new object[] {
                        UserId,
                        ProfileId}, this.getAllFacebookUserFeedOfUsersOperationCompleted, userState);
        }
        
        private void OngetAllFacebookUserFeedOfUsersOperationCompleted(object arg) {
            if ((this.getAllFacebookUserFeedOfUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllFacebookUserFeedOfUsersCompleted(this, new getAllFacebookUserFeedOfUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageDetailByMessageid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMessageDetailByMessageid(string MessageId) {
            object[] results = this.Invoke("GetMessageDetailByMessageid", new object[] {
                        MessageId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageDetailByMessageidAsync(string MessageId) {
            this.GetMessageDetailByMessageidAsync(MessageId, null);
        }
        
        /// <remarks/>
        public void GetMessageDetailByMessageidAsync(string MessageId, object userState) {
            if ((this.GetMessageDetailByMessageidOperationCompleted == null)) {
                this.GetMessageDetailByMessageidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageDetailByMessageidOperationCompleted);
            }
            this.InvokeAsync("GetMessageDetailByMessageid", new object[] {
                        MessageId}, this.GetMessageDetailByMessageidOperationCompleted, userState);
        }
        
        private void OnGetMessageDetailByMessageidOperationCompleted(object arg) {
            if ((this.GetMessageDetailByMessageidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageDetailByMessageidCompleted(this, new GetMessageDetailByMessageidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UserHomeWithLimitCompletedEventHandler(object sender, UserHomeWithLimitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserHomeWithLimitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserHomeWithLimitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UserHomeCompletedEventHandler(object sender, UserHomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserHomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserHomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getAllFacebookMessagesOfUserCompletedEventHandler(object sender, getAllFacebookMessagesOfUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllFacebookMessagesOfUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllFacebookMessagesOfUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getAllSentMessagesCompletedEventHandler(object sender, getAllSentMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllSentMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllSentMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllWallpostsOfProfileAccordingtoGroupCompletedEventHandler(object sender, GetAllWallpostsOfProfileAccordingtoGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllWallpostsOfProfileAccordingtoGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllWallpostsOfProfileAccordingtoGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getAllFacebookMessagesOfUserByProfileIdCompletedEventHandler(object sender, getAllFacebookMessagesOfUserByProfileIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllFacebookMessagesOfUserByProfileIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllFacebookMessagesOfUserByProfileIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getAllFacebookTagOfUsersCompletedEventHandler(object sender, getAllFacebookTagOfUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllFacebookTagOfUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllFacebookTagOfUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getAllFacebookstatusOfUsersCompletedEventHandler(object sender, getAllFacebookstatusOfUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllFacebookstatusOfUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllFacebookstatusOfUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getAllFacebookUserFeedOfUsersCompletedEventHandler(object sender, getAllFacebookUserFeedOfUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllFacebookUserFeedOfUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllFacebookUserFeedOfUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetMessageDetailByMessageidCompletedEventHandler(object sender, GetMessageDetailByMessageidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageDetailByMessageidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageDetailByMessageidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591